### ISSUE TITLE
graphql-mesh   grpc

### ISSUE THREAD

**Issue by day112** [Kiesen/graphql-mesh-express#37]
Is there graphql-mesh-grpc  demo ?

**Comment by angelsvirkov** [comment]
@day112 , we don't have a graphql-mesh-grpc demo so far. Maybe you would like to check the examples from the official repo https://github.com/Urigo/graphql-mesh/tree/master/examples/grpc-example together with the test file -> https://github.com/Urigo/graphql-mesh/blob/master/packages/handlers/grpc/test/handler.spec.ts
